### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by willm** [qualitybath/bunyan-slack#18]
Hi, I'm wondering if anyone is maintaining this package? It is used in various projects we work on and now is reporting some npm audit errors. We have created a fork of this package to get around this temporarily, would you still accept pull requests to it? alternatively we would be happy to maintain it ourselves if you would prefer to transfer ownership?

**Comment by tikotzky** [comment]
Hi @willm, We're still using this in our own projects and would be more than happy to review and accept PRs.
Let me know if there is anything I can do to assist.

**Comment by willm** [comment]
Hi @tikotzky I've made a pull request to fix a few problems and add a few things to this package https://github.com/qualitybath/bunyan-slack/pull/20

**Comment by tikotzky** [comment]
Hi @willm,

Thanks! I'll have it reviewed and let you know if I have any questions.
