### ISSUE TITLE
Usage of this in request error

### ISSUE THREAD

**Issue by sabrehagen** [qualitybath/bunyan-slack#7]
I see you have a test to make sure your error handler is being run. I can't run your tests on my machine as I receive the following error, but your travis-ci build suggests that the test passes.

In the following code block, in .on('error') you are returning `this.error`, but `this` will have lost its context when the error event fires, so you should really take a reference to `this` outside the request call, for example `var self = this`, then reference `return self.error(error)`. I believe your code will fail otherwise!

	request.post({
		url: this.webhook_url,
		body: JSON.stringify(message)
	})
	.on('error', function(err) {
		return this.error(err);
    });

My attempt at running your tests - maybe a mocha issue?
```
$ npm test

> bunyan-slack@0.0.8 test C:\repositories\bunyan-slack
> istanbul cover _mocha --report lcovonly

No coverage information was collected, exit without writing coverage information
C:\repositories\bunyan-slack\node_modules\.bin\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:449:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\repositories\bunyan-slack\node_modules\istanbul\lib\hook.js:107:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
    at runFn (C:\repositories\bunyan-slack\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\repositories\bunyan-slack\node_modules\istanbul\lib\command\common\run-with-cover.js:248:17
    at C:\repositories\bunyan-slack\node_modules\istanbul\lib\util\file-matcher.js:68:16
npm ERR! Test failed.  See above for more details.
```

**Comment by sethpollack** [comment]
Thanks for pointing that out! I fixed and added a test.

**Comment by sabrehagen** [comment]
I'm confused as to what this says about the test suite. How did it pass?

**Comment by tikotzky** [comment]
The tests were passing because there was no test asserting that the error
handler was called.

The issue was fixed and a test added to prevent regressions in the future.
